version: '3.4'

services:
  sqldata:
    environment:
      - POSTGRES_PASSWORD=Pass@word
    ports:
      - "1432:5432"
  musicsellerapp.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8930:80"       
  musicsellerapp.web.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8730:80"