version: '3.4'

services:
  sqldata:
    image: postgres:latest
  musicsellerapp.server:
    build:
      context: .
      dockerfile: MusicSellerApp.Server/Dockerfile
  musicsellerapp.web.mvc:
    build:
        context: .
        dockerfile: WebMvc/Dockerfile
  identity.api:
    build:
      context: .
      dockerfile: Identity.Api/Dockerfile
