version: '3.4'

services:
  musicsellerapp.server:
    image: ${DOCKER_REGISTRY-}musicsellerappserver
    build:
      context: .
      dockerfile: MusicSellerApp.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8930:80"
      
  musicsellerapp.web.mvc:
    build:
        context: .
        dockerfile: WebMvc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"